version: 0.2
env: 
  shell: bash
  exported-variables:
    - ENV_NAME
    - DEPLOYMENT_BUCKET
    - SourceCode1
    - SourceCode2
    - SourceCode3
    - SourceCode4

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - echo install started on `date`
      #- yum update -y
      - npm --version
      - echo install started on `date`

  build:
    commands:
      - echo Enter Deploy Build Phase `date`
      - echo ${SourceCode1}, ${SourceCode2}, ${SourceCode3}, ${SourceCode4}, ${ENV_NAME}, ${DEPLOYMENT_BUCKET}, ${CODEBUILD_SRC_DIR}
      # prepare build stage
      # Move assets to build staging directory
      - cd ../ && mkdir -p build/${SourceCode1} && cp -r ${CODEBUILD_SRC_DIR}/. build/${SourceCode1}
      # Remove flattened file layer directories
      - rm -rf ./build/${SourceCode2} ./build/${SourceCode3} ./build/${SourceCode4} 
      # Create layers directories and move assets into it
      - mkdir -p build/${SourceCode1}/layers/${SourceCode2}
      - mkdir -p build/${SourceCode1}/layers/${SourceCode3}
      - mkdir -p build/${SourceCode1}/layers/${SourceCode4}
      - cp -R ${CODEBUILD_SRC_DIR_SourceCode2}/. build/${SourceCode1}/layers/${SourceCode2}
      - cp -R ${CODEBUILD_SRC_DIR_SourceCode3}/. build/${SourceCode1}/layers/${SourceCode3}
      - cp -R ${CODEBUILD_SRC_DIR_SourceCode4}/. build/${SourceCode1}/layers/${SourceCode4}
      # Report staged content
      - cd ./build
      - echo build directory built location `pwd` 
      - echo Recursive list of directories `ls -R`
      - echo Exit Deploy Build Phase `date`
      
  post_build:
    commands:
      - echo Enter Deploy PostBuild Phase `date`
      - echo ${SourceCode1}, ${SourceCode2}, ${SourceCode3}, ${SourceCode4}, ${ENV_NAME}, ${DEPLOYMENT_BUCKET}, ${CODEBUILD_SRC_DIR}
      - cd ${SourceCode1}/scripts/deploy && echo `pwd`
      - chmod 755 deploy.sh && ./deploy.sh "${ENV_NAME}" "${DEPLOYMENT_BUCKET}" 
      - echo Exit Deploy PostBuild Phase `date`

