name: Full Deploy
on:
  push:
    branches:
      - main
jobs:
  pre_build:
    runs-on: ubuntu-latest
    steps: 
      - name: Get Fundation Repo
        uses: actions/checkout@v4

      - name: Checkout Utilities Repo
        uses: actions/checkout@v4
        with:
          repository: rodreinheimer/loyalty-ops-layer-utilities
          path: loyalty-ops-layer-utilities

      - name: Checkout Configuration Repo
        uses: actions/checkout@v4
        with:
          repository: rodreinheimer/loyalty-ops-layer-config
          path: loyalty-ops-layer-config

      - name: Checkout Modules Repo
        uses: actions/checkout@v4
        with:
          repository: rodreinheimer/loyalty-ops-layer-modules
          path: loyalty-ops-layer-modules

      - name: List Root Directory
        run: ls

      - name:
        run: echo install started on `date`

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16


