name: Full Deploy
on:
  pull_request:
    types: 
      - closed
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    environment: develop
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      PR_NUMBER: ${{ github.event.number }}

    steps:
      - name: List Root Directory
        run: echo "Add label to PR - ${{ vars.APP_DEPLOYING_LABEL }}"

      - name: Review github ref
        run:  echo "${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}"

      - name: Output GitHub context
        run: echo "${{ toJSON(github) }}"
