name: Full Deploy
on:
  push:
    branches:
      - main
jobs:
  pre_build:
    runs-on: ubuntu-latest
    environment: develop
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps: 
      - name: Get Fundation Repo
        uses: actions/checkout@v4
        with:
          path: loyalty-ops-layer-foundation/build

      - name: Checkout Utilities Repo
        uses: actions/checkout@v4
        with:
          repository: rodreinheimer/loyalty-ops-layer-utilities
          path: loyalty-ops-layer-foundation/build/layers/loyalty-ops-layer-utilities

      - name: Checkout Configuration Repo
        uses: actions/checkout@v4
        with:
          repository: rodreinheimer/loyalty-ops-layer-config
          path: loyalty-ops-layer-foundation/build/layers/loyalty-ops-layer-config

      - name: Checkout Modules Repo
        uses: actions/checkout@v4
        with:
          repository: rodreinheimer/loyalty-ops-layer-modules
          path: loyalty-ops-layer-foundation/build/layers/loyalty-ops-layer-modules

      - name: List Root Directory
        run: |
          echo '------------------------------------------------'
          echo 'ENV_NAME: ${{ vars.ENV_NAME }}'
          echo 'DEPLOYMENT_BUCKET: ${{ vars.DEPLOYMENT_BUCKET }}'
          echo 'ENV_NAME: ${{ vars.STACK_NAME }}'
          echo 'SOURCE_CODE_1: ${{ vars.SOURCE_CODE_1 }}'
          echo 'SOURCE_CODE_2: ${{ vars.SOURCE_CODE_2 }}'
          echo 'SOURCE_CODE_3: ${{ vars.SOURCE_CODE_3 }}'
          echo 'SOURCE_CODE_4: ${{ vars.SOURCE_CODE_4 }}'
          echo '------------------------------------------------'

      - name: Step into Build Directory
        run: |
          echo '------------------------------------------------'
          pwd
          ls -R
          echo '------------------------------------------------'
          cd ./build

      - name: List Root Directory
        run: |
          echo '------------------------------------------------'
          echo 'Build Location `pwd`'
          echo 'Recursive List `ls -R`'
          echo 'End Pre-build Phase `date`'
          echo '------------------------------------------------'

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build Modules
        run: |
          cd ../../layers/loyalty-ops-layer-modules/nodejs
          run: npm ci
          
      - name: Package Modules Layer
        run: |
          cd ../
          zip -vr layer_delta.zip nodejs/ -x "*.DS_Store"

      # Deploy to AWS CloudFormation
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ vars.STACK_NAME }}
          template: ./template.yml
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: "EnvType=${{ vars.ENV_NAME }}"





