name: Full Deploy
on:
  push:
    branches:
      - main
jobs:
  pre_build:
    runs-on: ubuntu-latest
    environment: develop
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps: 
      - name: Get Fundation Repo
        uses: actions/checkout@v4

      - name: Checkout Utilities Repo
        uses: actions/checkout@v4
        with:
          repository: rodreinheimer/loyalty-ops-layer-utilities
          path: loyalty-ops-layer-utilities

      - name: Checkout Configuration Repo
        uses: actions/checkout@v4
        with:
          repository: rodreinheimer/loyalty-ops-layer-config
          path: loyalty-ops-layer-config

      - name: Checkout Modules Repo
        uses: actions/checkout@v4
        with:
          repository: rodreinheimer/loyalty-ops-layer-modules
          path: loyalty-ops-layer-modules

      - name: List Root Directory
        run: |
        ls 
        echo 'ENV_NAME: ${{ vars.ENV_NAME }}'
        echo 'DEPLOYMENT_BUCKET: ${{ vars.DEPLOYMENT_BUCKET }}'
        echo 'ENV_NAME: ${{ vars.STACK_NAME }}'
        echo 'SOURCE_CODE_1: ${{ vars.SOURCE_CODE_1 }}'
        echo 'SOURCE_CODE_2: ${{ vars.SOURCE_CODE_2 }}'
        echo 'SOURCE_CODE_3: ${{ vars.SOURCE_CODE_3 }}'
        echo 'SOURCE_CODE_4: ${{ vars.SOURCE_CODE_4 }}'

      - name:
        run: echo install started on `date`

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16


