name: Full Deploy
on:
  push:
    branches:
      - main
jobs:
  pre_build:
    runs-on: ubuntu-latest
    steps: 
      - name: Get Fundation Repo
        uses: actions/checkout@v4
      - name: Checkout Utilities Repo
        uses: actions/checkout@v4
        with:
          repository: rodreinheimer/loyalty-ops-layer-utilities
          path: loyalty-ops-layer-utilities
      - name: List Root Directory
        run: ls