name: Full Deploy
on:
  pull_request:
    types: 
      - opened

    branches:
      - main
jobs:
  pre_build:
    runs-on: ubuntu-latest
    environment: develop
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps: 
      - name: Get Fundation Repo
        uses: actions/checkout@v  4
        with:
          path: build/loyalty-ops-layer-foundation

      - name: Checkout Configuration Repo
        uses: actions/checkout@v4
        with:
          repository: rodreinheimer/loyalty-ops-layer-config
          path: build/loyalty-ops-layer-foundation/layers/loyalty-ops-layer-config

      - name: List Root Directory
        run: |
          pwd
          ls -R
          echo '------------------------------------------------'
          echo 'ENV_NAME: ${{ vars.ENV_NAME }}'
          echo 'DEPLOYMENT_BUCKET: ${{ vars.DEPLOYMENT_BUCKET }}'
          echo 'ENV_NAME: ${{ vars.STACK_NAME }}'
          echo 'SOURCE_CODE_1: ${{ vars.SOURCE_CODE_1 }}'
          echo 'SOURCE_CODE_2: ${{ vars.SOURCE_CODE_2 }}'
          echo 'SOURCE_CODE_3: ${{ vars.SOURCE_CODE_3 }}'
          echo 'SOURCE_CODE_4: ${{ vars.SOURCE_CODE_4 }}'
          echo '------------------------------------------------'

      # Deploy to AWS CloudFormation
      - name: Deploy to AWS Sam Build
        uses: aws-actions/setup-sam@v2
      - run: sam deploy --debug --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides EnvType=${{ vars.ENV_NAME }} --template build/loyalty-ops-layer-foundation/template.yml --stack-name ${{ vars.STACK_NAME }} --s3-bucket ${{ vars.DEPLOYMENT_BUCKET }} --region ${{ env.AWS_REGION }} --capabilities CAPABILITY_NAMED_IAM 