name: Deploy the Pipeline Cloudformation
on:
  push:
    branches:
      - main

  workflow_dispatch:
jobs:
  pipeline_cloudformation:
    name: Pipeline Cloudformation
    runs-on: ubuntu-latest
    environment: develop
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ENV: ${{ secrets.AWS_ENV }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Print Info
        run: echo "sdfasdfssdfasd${{ env.AWS_ACCESS_KEY_ID }}"

      # Configure AWS Credential
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Deploy to AWS CloudFormation
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: loyalty-ops-config-layer-pipeline
          template: ./pipeline.yml
          parameter-overrides: "GitHubRepository=loyalty-ops-config-layer-pipeline-${{ env.AWS_ENV }}"