name: Deploy the Pipeline Cloudformation
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  pipeline_cloudformation:
    name: Pipeline Cloudformation
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3